# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de3afd9b5ed8388c75f5b8e6779f7cbcbc5832936c0527ff3b5ecaf197c2e70a1fb8ec25b8bb06ecff0fd7309ad297bef0665222f4afc8c750c0ce4332f32737

test:
  secret_key_base: 1a50f6b8ace9772aee4d02fc82e5901bf6df4dd1eaf734b5228be680513490fac3432cdc9691fecf0e6a2f9179c1f48436d2c3d1f32be7825d1fc3f364f50004

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
